# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'pipelines-javascript-docker'
  registryName: 'cmoretta-dockerhub'
  repoName: 'cmoretta-dockhub-repo'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
     $(cmoretta-dockerHub)
     repository: $(imageName)
    command: push
    tags: |
      test1
      test2
  #inputs:
  #  containerRegistry: |
  #    $(dockerhub) 
  #    username: ((docker-hub-username))
  #    password: ((docker-hub-password))
  #  repository: $(imageName)
  #  command: push
  #  tags: |
  #    test1
  #    test2
